# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: local
  hooks:
    - id: autopep8
      name: autopep8
      entry: poetry run autopep8 -i -aa
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: poetry run pylint -j 0 -E
      language: system
      types: [python]
